name: unit-tests-on-pull-requests
run-name: Run Unit Tests

on: [pull_request]

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node version 16.x.x
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install package dependencies
        run: npm install
      - name: Run tests
        run: npm run test
